version: '3'

services:
  pokedexapp:
    # IF YOU WANT TO INCLUDE MONGO DB AS WELL, UNCOMMENT JUST THE NEXT TWO LINE
    # depends_on:
    #   - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: pokedex-docker
    container_name: pokedexapp
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"
    # working_dir: /var/www/pokedex
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
    # volumes:
    #   - ./:/var/www/pokedex

  # IF YOU WANT TO INCLUDE MONGO DB AS WELL, UNCOMMENT LINES BELOW
  # db:
  #   image: mongo
  #   container_name: mongo-pokedex
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   environment:
  #     DATABASE_NAME: ${DATABASE_NAME}
  #   volumes:
  #     - ./mongo:/data/db