# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      # MONGO_INITDB_DATABASE: pokemons
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example123
    volumes:
      - ./mongo:/data/db